# -*- coding: utf-8 -*-
"""CIE-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7w8HJdPY2sbXeqsrcNi3DWdtTO9_5cR
"""

from scipy import stats
import pandas as pd
zscore=stats.zscore(df['Pclass'])
threshold=2
outlier=abs(zscore)>threshold
print(outlier)

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/DATA SET /titanic.csv')
df.describe()

df.info()

df.duplicated()

df['Age']. unique()



df.isnull()

from google.colab import drive
drive.mount('/content/drive')

df.corr()

"""CENTRAL TENDENCY"""

import pandas as pd
import statistics
df=pd.read_csv('/content/drive/MyDrive/DATA SET /titanic.csv')

AMean =df['Age'].mean()
Amedian=df['Age'].median()
Amode=statistics.mode(df['Age'])

print("Age_mean ",AMean)
print('Age_median',Amedian)
print('Age_mode',Amode)

fare_mean=df['Fare'].mean()
fare_median=df['Fare'].median()
fare_mode=statistics.mode(df['Fare'])

print('fare_mean',fare_mean)
print('fare_median',fare_median)
print('fare_mode',fare_mode)

import matplotlib.pyplot as plt
df['Survived'].replace({0:'not survived',1:' survived'},inplace= True)

survived_pclass_count = df.groupby(['Survived', 'Pclass']).size().unstack()
survived_pclass_count.plot(kind='bar')
plt.title('Survived vs. Pclass')
plt.xlabel('Survived')
plt.ylabel('Count')
plt.show()

# 3
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/DATA SET /titanic.csv')
nullage=df['Age'].isnull().sum()
print("before",nullage)
MeanAge=df['Age'].mean()
afterage=df['Age'].fillna(MeanAge,inplace=True)
print("after",MeanAge)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv('/content/drive/MyDrive/DATA SET /titanic.csv')
from scipy import stats
z_scores = np.abs(stats.zscore(df['Fare']))
threshold = 3
outliers = df['Fare'][z_scores > threshold]

sns.boxplot(x='Fare', data=df)
plt.title('Box Plot of Fare Column (with Outliers)')
plt.xlabel('Fare')
plt.show()
print("Outlier values for 'Fare' column:")
print(outliers)